package com.chan.cds.common.mapper;

import com.chan.cds.common.entity.CropAttachment;
import com.chan.cds.common.entity.CropAttachmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CropAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop_attachment
     *
     * @mbggenerated
     */
    int countByExample(CropAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop_attachment
     *
     * @mbggenerated
     */
    int deleteByExample(CropAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop_attachment
     *
     * @mbggenerated
     */
    int insert(CropAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop_attachment
     *
     * @mbggenerated
     */
    int insertSelective(CropAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop_attachment
     *
     * @mbggenerated
     */
    List<CropAttachment> selectByExampleWithRowbounds(CropAttachmentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop_attachment
     *
     * @mbggenerated
     */
    List<CropAttachment> selectByExample(CropAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop_attachment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CropAttachment record, @Param("example") CropAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop_attachment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CropAttachment record, @Param("example") CropAttachmentExample example);
}