package com.chan.cds.common.mapper;

import com.chan.cds.common.entity.Crop;
import com.chan.cds.common.entity.CropExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CropMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop
     *
     * @mbggenerated
     */
    int countByExample(CropExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop
     *
     * @mbggenerated
     */
    int deleteByExample(CropExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer cropId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop
     *
     * @mbggenerated
     */
    int insert(Crop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop
     *
     * @mbggenerated
     */
    int insertSelective(Crop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop
     *
     * @mbggenerated
     */
    List<Crop> selectByExampleWithBLOBsWithRowbounds(CropExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop
     *
     * @mbggenerated
     */
    List<Crop> selectByExampleWithBLOBs(CropExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop
     *
     * @mbggenerated
     */
    List<Crop> selectByExampleWithRowbounds(CropExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop
     *
     * @mbggenerated
     */
    List<Crop> selectByExample(CropExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop
     *
     * @mbggenerated
     */
    Crop selectByPrimaryKey(Integer cropId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Crop record, @Param("example") CropExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") Crop record, @Param("example") CropExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Crop record, @Param("example") CropExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Crop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(Crop record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Crop record);
}