package com.chan.cds.common.mapper;

import com.chan.cds.common.entity.DiseaseAttachment;
import com.chan.cds.common.entity.DiseaseAttachmentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface DiseaseAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_attachment
     *
     * @mbggenerated
     */
    int countByExample(DiseaseAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_attachment
     *
     * @mbggenerated
     */
    int deleteByExample(DiseaseAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_attachment
     *
     * @mbggenerated
     */
    int insert(DiseaseAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_attachment
     *
     * @mbggenerated
     */
    int insertSelective(DiseaseAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_attachment
     *
     * @mbggenerated
     */
    List<DiseaseAttachment> selectByExampleWithRowbounds(DiseaseAttachmentExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_attachment
     *
     * @mbggenerated
     */
    List<DiseaseAttachment> selectByExample(DiseaseAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_attachment
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") DiseaseAttachment record, @Param("example") DiseaseAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_attachment
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") DiseaseAttachment record, @Param("example") DiseaseAttachmentExample example);
}