package com.chan.cds.common.mapper;

import com.chan.cds.common.entity.SolvingWay;
import com.chan.cds.common.entity.SolvingWayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SolvingWayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solving_way
     *
     * @mbggenerated
     */
    int countByExample(SolvingWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solving_way
     *
     * @mbggenerated
     */
    int deleteByExample(SolvingWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solving_way
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer solveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solving_way
     *
     * @mbggenerated
     */
    int insert(SolvingWay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solving_way
     *
     * @mbggenerated
     */
    int insertSelective(SolvingWay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solving_way
     *
     * @mbggenerated
     */
    List<SolvingWay> selectByExampleWithBLOBsWithRowbounds(SolvingWayExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solving_way
     *
     * @mbggenerated
     */
    List<SolvingWay> selectByExampleWithBLOBs(SolvingWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solving_way
     *
     * @mbggenerated
     */
    List<SolvingWay> selectByExampleWithRowbounds(SolvingWayExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solving_way
     *
     * @mbggenerated
     */
    List<SolvingWay> selectByExample(SolvingWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solving_way
     *
     * @mbggenerated
     */
    SolvingWay selectByPrimaryKey(Integer solveId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solving_way
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SolvingWay record, @Param("example") SolvingWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solving_way
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") SolvingWay record, @Param("example") SolvingWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solving_way
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SolvingWay record, @Param("example") SolvingWayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solving_way
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SolvingWay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solving_way
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SolvingWay record);
}