package com.chan.cds.common.entity;

import java.util.Date;

public class Attachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.attachment_id
     *
     * @mbggenerated
     */
    private Integer attachmentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.name_en
     *
     * @mbggenerated
     */
    private String nameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.name_mm
     *
     * @mbggenerated
     */
    private String nameMm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.created_date
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.updated_date
     *
     * @mbggenerated
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attachment.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.attachment_id
     *
     * @return the value of attachment.attachment_id
     *
     * @mbggenerated
     */
    public Integer getAttachmentId() {
        return attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.attachment_id
     *
     * @param attachmentId the value for attachment.attachment_id
     *
     * @mbggenerated
     */
    public void setAttachmentId(Integer attachmentId) {
        this.attachmentId = attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.name_en
     *
     * @return the value of attachment.name_en
     *
     * @mbggenerated
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.name_en
     *
     * @param nameEn the value for attachment.name_en
     *
     * @mbggenerated
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.name_mm
     *
     * @return the value of attachment.name_mm
     *
     * @mbggenerated
     */
    public String getNameMm() {
        return nameMm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.name_mm
     *
     * @param nameMm the value for attachment.name_mm
     *
     * @mbggenerated
     */
    public void setNameMm(String nameMm) {
        this.nameMm = nameMm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.created_by
     *
     * @return the value of attachment.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.created_by
     *
     * @param createdBy the value for attachment.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.created_date
     *
     * @return the value of attachment.created_date
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.created_date
     *
     * @param createdDate the value for attachment.created_date
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.updated_by
     *
     * @return the value of attachment.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.updated_by
     *
     * @param updatedBy the value for attachment.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.updated_date
     *
     * @return the value of attachment.updated_date
     *
     * @mbggenerated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.updated_date
     *
     * @param updatedDate the value for attachment.updated_date
     *
     * @mbggenerated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attachment.description
     *
     * @return the value of attachment.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attachment.description
     *
     * @param description the value for attachment.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attachment
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", attachmentId=").append(attachmentId);
        sb.append(", nameEn=").append(nameEn);
        sb.append(", nameMm=").append(nameMm);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append(", description=").append(description);
        sb.append("]");
        return sb.toString();
    }
}