package com.chan.cds.common.entity;

public class CropAttachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crop_attachment.crop_id
     *
     * @mbggenerated
     */
    private Integer cropId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crop_attachment.attachment_id
     *
     * @mbggenerated
     */
    private Integer attachmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crop_attachment.crop_id
     *
     * @return the value of crop_attachment.crop_id
     *
     * @mbggenerated
     */
    public Integer getCropId() {
        return cropId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crop_attachment.crop_id
     *
     * @param cropId the value for crop_attachment.crop_id
     *
     * @mbggenerated
     */
    public void setCropId(Integer cropId) {
        this.cropId = cropId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crop_attachment.attachment_id
     *
     * @return the value of crop_attachment.attachment_id
     *
     * @mbggenerated
     */
    public Integer getAttachmentId() {
        return attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crop_attachment.attachment_id
     *
     * @param attachmentId the value for crop_attachment.attachment_id
     *
     * @mbggenerated
     */
    public void setAttachmentId(Integer attachmentId) {
        this.attachmentId = attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop_attachment
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cropId=").append(cropId);
        sb.append(", attachmentId=").append(attachmentId);
        sb.append("]");
        return sb.toString();
    }
}