package com.chan.cds.common.entity;

import java.util.Date;

public class Crop {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crop.crop_id
     *
     * @mbggenerated
     */
    private Integer cropId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crop.name_en
     *
     * @mbggenerated
     */
    private String nameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crop.name_mm
     *
     * @mbggenerated
     */
    private String nameMm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crop.bio_name
     *
     * @mbggenerated
     */
    private String bioName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crop.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crop.created_date
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crop.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crop.updated_date
     *
     * @mbggenerated
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crop.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crop.crop_id
     *
     * @return the value of crop.crop_id
     *
     * @mbggenerated
     */
    public Integer getCropId() {
        return cropId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crop.crop_id
     *
     * @param cropId the value for crop.crop_id
     *
     * @mbggenerated
     */
    public void setCropId(Integer cropId) {
        this.cropId = cropId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crop.name_en
     *
     * @return the value of crop.name_en
     *
     * @mbggenerated
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crop.name_en
     *
     * @param nameEn the value for crop.name_en
     *
     * @mbggenerated
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crop.name_mm
     *
     * @return the value of crop.name_mm
     *
     * @mbggenerated
     */
    public String getNameMm() {
        return nameMm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crop.name_mm
     *
     * @param nameMm the value for crop.name_mm
     *
     * @mbggenerated
     */
    public void setNameMm(String nameMm) {
        this.nameMm = nameMm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crop.bio_name
     *
     * @return the value of crop.bio_name
     *
     * @mbggenerated
     */
    public String getBioName() {
        return bioName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crop.bio_name
     *
     * @param bioName the value for crop.bio_name
     *
     * @mbggenerated
     */
    public void setBioName(String bioName) {
        this.bioName = bioName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crop.created_by
     *
     * @return the value of crop.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crop.created_by
     *
     * @param createdBy the value for crop.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crop.created_date
     *
     * @return the value of crop.created_date
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crop.created_date
     *
     * @param createdDate the value for crop.created_date
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crop.updated_by
     *
     * @return the value of crop.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crop.updated_by
     *
     * @param updatedBy the value for crop.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crop.updated_date
     *
     * @return the value of crop.updated_date
     *
     * @mbggenerated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crop.updated_date
     *
     * @param updatedDate the value for crop.updated_date
     *
     * @mbggenerated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crop.description
     *
     * @return the value of crop.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crop.description
     *
     * @param description the value for crop.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crop
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cropId=").append(cropId);
        sb.append(", nameEn=").append(nameEn);
        sb.append(", nameMm=").append(nameMm);
        sb.append(", bioName=").append(bioName);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append(", description=").append(description);
        sb.append("]");
        return sb.toString();
    }
}