package com.chan.cds.common.entity;

import java.util.Date;

public class Disease {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.disease_id
     *
     * @mbggenerated
     */
    private Integer diseaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.name_en
     *
     * @mbggenerated
     */
    private String nameEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.name_mm
     *
     * @mbggenerated
     */
    private String nameMm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.created_by
     *
     * @mbggenerated
     */
    private String createdBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.created_date
     *
     * @mbggenerated
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.updated_by
     *
     * @mbggenerated
     */
    private String updatedBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.updated_date
     *
     * @mbggenerated
     */
    private Date updatedDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.disease_id
     *
     * @return the value of disease.disease_id
     *
     * @mbggenerated
     */
    public Integer getDiseaseId() {
        return diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.disease_id
     *
     * @param diseaseId the value for disease.disease_id
     *
     * @mbggenerated
     */
    public void setDiseaseId(Integer diseaseId) {
        this.diseaseId = diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.name_en
     *
     * @return the value of disease.name_en
     *
     * @mbggenerated
     */
    public String getNameEn() {
        return nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.name_en
     *
     * @param nameEn the value for disease.name_en
     *
     * @mbggenerated
     */
    public void setNameEn(String nameEn) {
        this.nameEn = nameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.name_mm
     *
     * @return the value of disease.name_mm
     *
     * @mbggenerated
     */
    public String getNameMm() {
        return nameMm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.name_mm
     *
     * @param nameMm the value for disease.name_mm
     *
     * @mbggenerated
     */
    public void setNameMm(String nameMm) {
        this.nameMm = nameMm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.created_by
     *
     * @return the value of disease.created_by
     *
     * @mbggenerated
     */
    public String getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.created_by
     *
     * @param createdBy the value for disease.created_by
     *
     * @mbggenerated
     */
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.created_date
     *
     * @return the value of disease.created_date
     *
     * @mbggenerated
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.created_date
     *
     * @param createdDate the value for disease.created_date
     *
     * @mbggenerated
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.updated_by
     *
     * @return the value of disease.updated_by
     *
     * @mbggenerated
     */
    public String getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.updated_by
     *
     * @param updatedBy the value for disease.updated_by
     *
     * @mbggenerated
     */
    public void setUpdatedBy(String updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.updated_date
     *
     * @return the value of disease.updated_date
     *
     * @mbggenerated
     */
    public Date getUpdatedDate() {
        return updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.updated_date
     *
     * @param updatedDate the value for disease.updated_date
     *
     * @mbggenerated
     */
    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease.description
     *
     * @return the value of disease.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease.description
     *
     * @param description the value for disease.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", diseaseId=").append(diseaseId);
        sb.append(", nameEn=").append(nameEn);
        sb.append(", nameMm=").append(nameMm);
        sb.append(", createdBy=").append(createdBy);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", updatedBy=").append(updatedBy);
        sb.append(", updatedDate=").append(updatedDate);
        sb.append(", description=").append(description);
        sb.append("]");
        return sb.toString();
    }
}