package com.chan.cds.common.entity;

public class DiseaseAttachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_attachment.disease_id
     *
     * @mbggenerated
     */
    private Integer diseaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column disease_attachment.attachment_id
     *
     * @mbggenerated
     */
    private Integer attachmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_attachment.disease_id
     *
     * @return the value of disease_attachment.disease_id
     *
     * @mbggenerated
     */
    public Integer getDiseaseId() {
        return diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_attachment.disease_id
     *
     * @param diseaseId the value for disease_attachment.disease_id
     *
     * @mbggenerated
     */
    public void setDiseaseId(Integer diseaseId) {
        this.diseaseId = diseaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column disease_attachment.attachment_id
     *
     * @return the value of disease_attachment.attachment_id
     *
     * @mbggenerated
     */
    public Integer getAttachmentId() {
        return attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column disease_attachment.attachment_id
     *
     * @param attachmentId the value for disease_attachment.attachment_id
     *
     * @mbggenerated
     */
    public void setAttachmentId(Integer attachmentId) {
        this.attachmentId = attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table disease_attachment
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", diseaseId=").append(diseaseId);
        sb.append(", attachmentId=").append(attachmentId);
        sb.append("]");
        return sb.toString();
    }
}