package com.chan.cds.common.entity;

public class SolvingAttachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solving_attachment.solve_id
     *
     * @mbggenerated
     */
    private Integer solveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solving_attachment.attachment_id
     *
     * @mbggenerated
     */
    private Integer attachmentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solving_attachment.solve_id
     *
     * @return the value of solving_attachment.solve_id
     *
     * @mbggenerated
     */
    public Integer getSolveId() {
        return solveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solving_attachment.solve_id
     *
     * @param solveId the value for solving_attachment.solve_id
     *
     * @mbggenerated
     */
    public void setSolveId(Integer solveId) {
        this.solveId = solveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solving_attachment.attachment_id
     *
     * @return the value of solving_attachment.attachment_id
     *
     * @mbggenerated
     */
    public Integer getAttachmentId() {
        return attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solving_attachment.attachment_id
     *
     * @param attachmentId the value for solving_attachment.attachment_id
     *
     * @mbggenerated
     */
    public void setAttachmentId(Integer attachmentId) {
        this.attachmentId = attachmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solving_attachment
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", solveId=").append(solveId);
        sb.append(", attachmentId=").append(attachmentId);
        sb.append("]");
        return sb.toString();
    }
}