package com.chan.cds.common.entity;

public class SolvingWay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solving_way.solve_id
     *
     * @mbggenerated
     */
    private Integer solveId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column solving_way.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solving_way.solve_id
     *
     * @return the value of solving_way.solve_id
     *
     * @mbggenerated
     */
    public Integer getSolveId() {
        return solveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solving_way.solve_id
     *
     * @param solveId the value for solving_way.solve_id
     *
     * @mbggenerated
     */
    public void setSolveId(Integer solveId) {
        this.solveId = solveId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column solving_way.description
     *
     * @return the value of solving_way.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column solving_way.description
     *
     * @param description the value for solving_way.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table solving_way
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", solveId=").append(solveId);
        sb.append(", description=").append(description);
        sb.append("]");
        return sb.toString();
    }
}